### PR TITLE
Update for 1.2.1

### PR DESCRIPTION
**Pull request by shatyuka**
Notification won't disappear, maybe related to R2API.

### CODE REVIEW

**Comment by tristanmcpherson** [comment]
Yeah I’ll have to try to recompile for the latest R2API. We’re you able to test if this fixed the issue?

**Comment by shatyuka** [comment]
This PR aims to get this mod loaded.
Notification is another issue, it fails to destory itself. I don't know whether it should be handled by us or R2API goes wrong.

**Comment by shatyuka** [comment]
also, not working for multiplayer clients

**Comment by tristanmcpherson** [comment]
> also, not working for multiplayer clients

I should be able to take some time tomorrow to look at this and hopefully get the mod up and running. Otherwise it’ll have to wait till I get back from my trip this weekend. Sorry for the delay

**Comment by shatyuka** [comment]
Finally it works.

**Comment by shatyuka** [comment]
So could you merge this?

**Comment by tristanmcpherson** [comment]
Sorry, been busy with a lot of stuff. Thanks for the contribution! I’ll try to get a build up on thunderstore soon.

**Pull request merged**
